# Generated by Django 5.0.6 on 2024-06-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personal',
            unique_together=set(),
        ),
    ]
