# Generated by Django 5.0.6 on 2024-06-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_count', models.IntegerField(default=0)),
                ('competitive_count', models.IntegerField(default=0)),
                ('personal_highest', models.IntegerField(default=0)),
                ('competitive_highest', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.exercises')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exercise_type')},
            },
        ),
    ]
